language: ruby
services:
  - docker
rvm:
  - 2.5.0
  - 2.6.2
gemfile:
  - gemfiles/rails_5_2.gemfile
bundler_args: --without local
before_install:
  - gem install bundler
  - bundle install --gemfile=multi
env:
  RUBY_GC_MALLOC_LIMIT: 90000000
  RUBY_GC_HEAP_FREE_SLOTS: 200000
matrix:
  exclude:
    - rvm: 2.5.0
      gemfile: gemfiles/rails_5_2.gemfile
    - rvm: 2.6.2
      gemfile: gemfiles/rails_5_2.gemfile
  fast_finish: true
services: postgresql
cache: bundler
